### ISSUE TITLE
Connection Timedout

### ISSUE THREAD

**Issue by bocsitomcsi** [RobHofmann/HomeAssistant-GreeClimateComponent#17] opened 2019-05-27 19:46 UTC
**Describe the bug**
Sporadically the connection is timed out between the HAS instance and GREE AC. Two Comfort X AC are placed in the flat and got a static IP address. The issue causes service outage of gree component.

```
2019-05-27 21:19:32 INFO (MainThread) [custom_components.gree.climate] name(): Livingroom AC
2019-05-27 21:19:32 INFO (MainThread) [custom_components.gree.climate] supported_features(): 4801
2019-05-27 21:19:32 INFO (SyncWorker_3) [custom_components.gree.climate] update()
2019-05-27 21:19:32 INFO (SyncWorker_3) [custom_components.gree.climate] Starting SyncState
2019-05-27 21:19:32 INFO (SyncWorker_3) [custom_components.gree.climate] Fetching(192.168.0.16, 7000, 10, {"cid":"app","i":0,"pack":"6LzEUcYr4hmHnV32fNv240aHdxLcp/fFBt1k/8Dd1A1Rgs/OVhL5EZpGV5E2n9oMtx+8uHMk0/LWP5FJI7BOr4is+KDNIIZzaKdd+Ima
ZLn39YlGV8lLhXDHuqGfRzxEb3B5+WoAEQNRGQPVlmeOQV4Ui87oc6fUJTeHeiqk15bngeY+mzwTR1+Hy71jJ1VWk3jS1sFwrRlMAT1JRXbI3p7SBcso7HnAurv41nE9slu/i1EHocLv81Z1Z5w6bbSW8yDGX0AJvocSvBdZ+daJETTKhu3d6AP3rRPgHt26hLU=","t":"pack","tcid":"f4911e66da91","uid":
0})
2019-05-27 21:19:41 INFO (SyncWorker_10) [root] Sending control command: KEY
2019-05-27 21:19:42 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.bedroom_ac is taking over 10 seconds
2019-05-27 21:19:42 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.bedroom_ac fails
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gree/climate.py", line 548, in update
    self.SyncState()
  File "/config/custom_components/gree/climate.py", line 365, in SyncState
    currentValues = self.GreeGetValues(optionsToFetch)
  File "/config/custom_components/gree/climate.py", line 217, in GreeGetValues
    return self.FetchResult(self.CIPHER, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['dat']
  File "/config/custom_components/gree/climate.py", line 196, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out
```

**To Reproduce**
Most of the time it can be reproducible when HAS is restarted or wait enough time.

**Configuration**
climate:
  - platform: gree
    name: Livingroom AC
    host: 192.168.0.15
    port: 7000
    mac: F4:91:1E:66:8C:80
    target_temp_step: 1
  - platform: gree
    name: Bedroom AC
    host: 192.168.0.16
    port: 7000
    mac: F4:91:1E:66:DA:91
    target_temp_step: 1

**Expected behavior**
It is expected to prevent connection timeout.

**Screenshots**

**Platform:**
 - OS: HAS in a docker
 - Browser: chrome
 - Version: saw from 0.91.0 - 0.93.2

**Comment by RobHofmann** [comment] 2019-05-28 16:13
I noticed this as well. I'm running HASSIO on 0.93.2. I havent found a fix so far. The issue isnt blocking in operating the device though, it's only an annoying warning in the logging.

Im not sure why this is happening. We will need more investigation on this.

**Comment by RobHofmann** [comment] 2019-07-10 08:41
I dont have this error anymore in HASS 0.95. I'm going to close this for now. Feel free to reopen if you still encounter this issue.

**Closed by RobHofmann** 2019-07-10 08:41 UTC
Labels: bug, help wanted

**Comment by bocsitomcsi** [comment] 2019-07-28 07:17
Hi, sorry for the late reply but now I can confirm it. I do not see any warning or error message with HASS 0.96.4. Thanks for the help.
