### ISSUE TITLE
Fan in Quiet Mode

### ISSUE THREAD

**Issue by spyko** [RobHofmann/HomeAssistant-GreeClimateComponent#35] opened 2019-07-31 14:38 UTC
Hi,
The problem remains.
(https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/33)

I turned on debug logging.
When I open the HVAC from HA, it goes to low. I suppose that it the gree component defaults to low.

Then I choose Quiet and the fan goes louder!
It is very strange behaviour.
Below the debug logs the moment I choose quiet:

2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] set_fan_mode(): Quiet
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Enabling quiet mode
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Starting SyncState
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Fetching(................)
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting acOptions with retrieved HVAC values
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting Pow: 1
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting Mod: 1
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting SetTem: 25
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting WdSpd: 1
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting Air: 0
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting Blo: 0
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting Health: 1
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting SwhSlp: 0
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting Lig: 1
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting SwingLfRig: 4
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting SwUpDn: 2
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting Quiet: 0
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting Tur: 0
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting StHt: 0
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting TemUn: 0
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting HeatCoolType: 0
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting TemRec: 0
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Setting SvSt: 0
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Done setting acOptions
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Overwriting acOptions with new settings
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Overwriting Tur: 0
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Overwriting Quiet: 1
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Done overwriting acOptions
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Start sending state to HVAC
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Done sending state to HVAC: {'t': 'res', 'mac': '.............', 'r': 200, 'opt': ['Pow', 'Mod', 'SetTem', 'WdSpd', 'Air', 'Blo', 'Health', 'SwhSlp', 'Lig', 'SwingLfRig', 'SwUpDn', 'Quiet', 'Tur', 'StHt', 'TemUn', 'HeatCoolType', 'TemRec', 'SvSt'], 'p': [1, 1, 25, 1, 0, 0, 1, 0, 1, 4, 2, 1, 0, 0, 0, 0, 0, 0], 'val': [1, 1, 25, 1, 0, 0, 1, 0, 1, 4, 2, 1, 0, 0, 0, 0, 0, 0]}
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] HA target temp set according to HVAC state to: 25
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] HA lights option set according to HVAC state to: on
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] HA health option set according to HVAC state to: on
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] HA health option set according to HVAC state to: on
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] HA powersave option set according to HVAC state to: off
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] HA sleep option set according to HVAC state to: off
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] HA operation mode set according to HVAC state to: cool
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] HA swing mode set according to HVAC state to: Fixed in the upmost position
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] HA fan mode set according to HVAC state to: Quiet
2019-07-30 22:37:23 INFO (SyncWorker_2) [custom_components.gree.climate] Finished SyncState
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] hvac_mode(): cool
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] supported_features(): 41
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] hvac_modes(): ['auto', 'cool', 'dry', 'fan_only', 'heat', 'off']
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] current_temperature(): None
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] temperature_unit(): °C
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] min_temp(): 16
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] temperature_unit(): °C
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] max_temp(): 30
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] temperature_unit(): °C
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] target_temperature_step(): 1.0
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] target_temperature_step(): 1.0
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] target_temperature(): 25
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] temperature_unit(): °C
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] fan_mode(): Quiet
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] fan_list(): ['Auto', 'low', 'Medium-Low', 'medium', 'Medium-High', 'high', 'Turbo', 'Quiet']
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] swing_mode(): Fixed in the upmost position
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] swing_modes(): ['Default', 'Swing in full range', 'Fixed in the upmost position', 'Fixed in the middle-up position', 'Fixed in the middle position', 'Fixed in the middle-low position', 'Fixed in the lowest position', 'Swing in the downmost region', 'Swing in the middle-low region', 'Swing in the middle region', 'Swing in the middle-up region', 'Swing in the upmost region']
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] name(): Hall AC
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] supported_features(): 41
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] should_poll()
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] update()
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Starting SyncState
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Fetching(..............)
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting acOptions with retrieved HVAC values
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting Pow: 1
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting Mod: 1
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting SetTem: 25
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting WdSpd: 1
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting Air: 0
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting Blo: 0
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting Health: 1
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting SwhSlp: 0
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting Lig: 1
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting SwingLfRig: 4
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting SwUpDn: 2
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting Quiet: 1
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting Tur: 0
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting StHt: 0
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting TemUn: 0
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting HeatCoolType: 0
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting TemRec: 0
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Setting SvSt: 0
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Done setting acOptions
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] HA target temp set according to HVAC state to: 25
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] HA lights option set according to HVAC state to: on
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] HA health option set according to HVAC state to: on
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] HA health option set according to HVAC state to: on
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] HA powersave option set according to HVAC state to: off
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] HA sleep option set according to HVAC state to: off
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] HA operation mode set according to HVAC state to: cool
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] HA swing mode set according to HVAC state to: Fixed in the upmost position
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] HA fan mode set according to HVAC state to: Quiet
2019-07-30 22:37:23 INFO (SyncWorker_4) [custom_components.gree.climate] Finished SyncState
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] hvac_mode(): cool
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] supported_features(): 41
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] hvac_modes(): ['auto', 'cool', 'dry', 'fan_only', 'heat', 'off']
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] current_temperature(): None
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] temperature_unit(): °C
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] min_temp(): 16
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] temperature_unit(): °C
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] max_temp(): 30
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] temperature_unit(): °C
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] target_temperature_step(): 1.0
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] target_temperature_step(): 1.0
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] target_temperature(): 25
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] temperature_unit(): °C
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] fan_mode(): Quiet
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] fan_list(): ['Auto', 'low', 'Medium-Low', 'medium', 'Medium-High', 'high', 'Turbo', 'Quiet']
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] swing_mode(): Fixed in the upmost position
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] swing_modes(): ['Default', 'Swing in full range', 'Fixed in the upmost position', 'Fixed in the middle-up position', 'Fixed in the middle position', 'Fixed in the middle-low position', 'Fixed in the lowest position', 'Swing in the downmost region', 'Swing in the middle-low region', 'Swing in the middle region', 'Swing in the middle-up region', 'Swing in the upmost region']
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] name(): Hall AC
2019-07-30 22:37:23 INFO (MainThread) [custom_components.gree.climate] supported_features(): 41

**Comment by spyko** [comment] 2019-08-01 04:48
Also, it looses the parameters such as X-fan, health, etc.

S.

**Comment by RobHofmann** [comment] 2019-08-01 08:35
I've tried this. I'm unable to reproduce. Quiet actually goes really quiet for me.

If you look at what your HASS is sending:
The WdSpd parameter gets set to 1, which means "low" in gree protocol.
The Quiet parameter gets set to 1, which means quiet mode is enabled.

Im not sure, but this sounds like the AC hasn't implemented the gree protocol fully right. I could be wrong, but from what I see in your logging, this sounds the most logical right now.

I'll look into adding some extra debugging information to see what you get back from the AC. Then we can change the settings through your remote control and read it with home assistant. Then we will know for sure.

Im not sure when I get to this. Its a busy period for me, but this will be on my todo list ;)

**Comment by RobHofmann** [comment] 2019-10-04 17:54
I've tested this more, but im unable to reproduce this. If you have more info on this, please let me know.

Closing this for now.

**Closed by RobHofmann** 2019-10-04 17:54 UTC
Labels: bug, unable to reproduce

**Comment by DuDe-75** [comment] 2024-07-14 07:35
Hello,

I've found this thread after some googling, and although it is closed, I'd like to add what I've found.
I have a GREE AC device (GWH12AGB), Home Assistant recongnizes it, and while it does not have the Quiet mode in the fan modes (screenshot 1), it does have a switch entity for quiet mode (screenshot 2).

![image](https://github.com/user-attachments/assets/a3d96884-bab8-4813-806b-136526633d46)

![image](https://github.com/user-attachments/assets/1e3624da-26c0-44f1-ab09-3c4abf5ee886)

When I use the remote for the AC to turn on Quiet mode, the switch in Home Assistant flips on/off, and Quiet mode is indeed quiet, but when I use the switch from Home Assistant to turn on Quiet mode, the fan goes louder then low (as written by OP).

**Comment by DuDe-75** [comment] 2024-07-15 19:23
> Hello,
> 
> I've found this thread after some googling, and although it is closed, I'd like to add what I've found. I have a GREE AC device (GWH12AGB), Home Assistant recongnizes it, and while it does not have the Quiet mode in the fan modes (screenshot 1), it does have a switch entity for quiet mode (screenshot 2).
> 
> ![image](https://private-user-images.githubusercontent.com/53651883/348521605-a3d96884-bab8-4813-806b-136526633d46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzE1MzIsIm5iZiI6MTcyMTA3MTIzMiwicGF0aCI6Ii81MzY1MTg4My8zNDg1MjE2MDUtYTNkOTY4ODQtYmFiOC00ODEzLTgwNmItMTM2NTI2NjMzZDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE5MjAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZDkzYjMzMjUzMjE1YjFlNmNhMTEyNDM5NGVkNTk2MzNkYzg0MWM5YmE1NjRmYzZkODJhOWRiNGMyMDI1YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.liLlXx2WaMvC--Rw17nWl8IMYDMaVkcFfoyAMeqJZc8)
> 
> ![image](https://private-user-images.githubusercontent.com/53651883/348521665-1e3624da-26c0-44f1-ab09-3c4abf5ee886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzE1MzIsIm5iZiI6MTcyMTA3MTIzMiwicGF0aCI6Ii81MzY1MTg4My8zNDg1MjE2NjUtMWUzNjI0ZGEtMjZjMC00NGYxLWFiMDktM2M0YWJmNWVlODg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE5MjAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMTZjMDY0NWMxMmZmZTYzYTc0MzQ1YTdhM2E0MDJmNTZkMjJhMGQ1MGFhOWU3OGY1MGJjNDI3OWM4NTFjZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m-ivyEXlGNkMqCTeiGXHlpjbBnDhGQNB5eKUJQtEO9I)
> 
> When I use the remote for the AC to turn on Quiet mode, the switch in Home Assistant flips on/off, and Quiet mode is indeed quiet, but when I use the switch from Home Assistant to turn on Quiet mode, the fan goes louder then low (as written by OP).

OK, nevermind...today it's working like it should. Yesterday I was updating my Home Assistant container (current core version: 2024.7.2), maybe that did the trick - haven't read the changelog yet 🤷🏼‍♂️😅

**Comment by boris-bc** [comment] 2024-11-22 13:07
There are two quite modes and it seems the integration is setting the Quiet Auto mode, which will allow the fan to blow faster. So the question here is how to enable the Quiet (versus Quiet Auto) mode.
