### ISSUE TITLE
Temperature Sensor

### ISSUE THREAD

**Issue by spyko** [RobHofmann/HomeAssistant-GreeClimateComponent#28] opened 2019-07-15 19:20 UTC
I cannot see the current temperature sensor neither in the graph nor anywhere else in Home Assistant.
Also, the HVAC is not showing up in Entity Registry. However, I can see it under the developer tools menu.

climate.yaml
- platform: gree
  name: Hall AC
  host: 192.168.***.***
  port: 7000
  mac: '**:**:**:**:**:**'
  target_temp_step: 1
  temp_sensor: sensor.ac_hall_temp

**Expected behavior**
Current Temperature should be in the graph and in general it should be in entity registry.

**Platform:**
 - OS: HASSIO
 - Version: 0.95.4
-  HVAC: Toyotomi KURO

From Debug Logs:
2019-07-15 20:22:19 INFO (MainThread) [custom_components.gree.climate] current_temperature(): None

I suppose that this shouldn't be None as well. Maybe that's why is not showing up in the graph.

Thank you in advance.

**Comment by RobHofmann** [comment] 2019-07-15 22:02
Is sensor.ac_hall_temp an existing sensor? Does it already show in your HASS before adding the Gree Component?

The temp_sensor property is to link an existing temperature sensor to the AC (so an external temperature sensor). Therefore it must exist before adding Gree.

As far as I know Gree does not support an internal temperature sensor for reading (only to set the target temperature).

Let me know if this helps

**Comment by spyko** [comment] 2019-07-16 06:59
OK, that makes sense then. I thought that it would read the internal temperature sensor of the HVAC.

Regarding the second part of my question. Why the HVAC's are not being showed in the Entity Registry of the configuration page?

**Comment by RobHofmann** [comment] 2019-07-16 08:33
This likely means that the setup of the component wasnt succesful. Can you turn on debug logging and post the logs?

PS. Don't forget to remove the "temp_sensor: sensor.ac_hall_temp" from your config. This will break your setup. Also I assume the MAC address is masked and is valid in your real config.

**Comment by spyko** [comment] 2019-07-16 15:12
In general, I can control the HVACs.
They are showed up in Front End as well as in developer tools, but not in Entity Registry. Of course I cannot add them in the integration pages. I suppose this is normal as it is a custom component.
<img width="771" alt="1" src="https://user-images.githubusercontent.com/3583302/61306392-320c3e00-a7f5-11e9-9ae3-5bf1a457ab83.PNG">
<img width="579" alt="2" src="https://user-images.githubusercontent.com/3583302/61306393-32a4d480-a7f5-11e9-8de9-26c3b0cfdf02.PNG">
<img width="827" alt="3" src="https://user-images.githubusercontent.com/3583302/61306396-333d6b00-a7f5-11e9-8969-418a9082d663.PNG">

**Comment by RobHofmann** [comment] 2019-07-18 11:40
Oh thats correct. I don't see it either. If you need to change something, you can use customize.yaml to change the display name etc.

Closing this for now since it's expected behaviour. If you feel something is wrong, please reopen this issue!

**Closed by RobHofmann** 2019-07-18 11:40 UTC
Labels: question

**Comment by drynish** [comment] 2021-01-15 19:50
I might be late for asking a question here, however since it's related. What I want to know is if I can achieve the following: 

Setting the sensor as a smart thermostat located in a central position in my house which will provide the current temperature and the hvac would work until that thermostat has reached the right temperature.

I was able to transfer the info from the thermostat to a sensor and using that sensor right into my gree custom component and the current temperature is showing in my lovelace diagram, but will the hvac uses that current temperature for it's decision?
