### ISSUE TITLE
Please add support for 8C heating, multiple devices in log

### ISSUE THREAD

**Issue by wacher74** [RobHofmann/HomeAssistant-GreeClimateComponent#46] opened 2019-12-20 15:10 UTC
Hello,

Could you add support of StHt (8 Celsius heating)?
I see in the logs that it is recognized but I can't see how to handle it via switches or inputbooleans.

Could you add an ID to log lines? 
I have two AC, I can't recognize now which lines are related to AC1 and which are related to AC2

$ grep "Setting StHt" *.log
2019-12-20 15:56:24 INFO (MainThread) [custom_components.gree.climate] Setting StHt: 1
2019-12-20 15:56:24 INFO (MainThread) [custom_components.gree.climate] Setting StHt: 0
2019-12-20 15:57:26 INFO (SyncWorker_4) [custom_components.gree.climate] Setting StHt: 1
2019-12-20 15:57:26 INFO (SyncWorker_0) [custom_components.gree.climate] Setting StHt: 0
2019-12-20 15:58:27 INFO (SyncWorker_4) [custom_components.gree.climate] Setting StHt: 0
2019-12-20 15:58:27 INFO (SyncWorker_0) [custom_components.gree.climate] Setting StHt: 1
2019-12-20 15:59:28 INFO (SyncWorker_4) [custom_components.gree.climate] Setting StHt: 0
2019-12-20 15:59:28 INFO (SyncWorker_0) [custom_components.gree.climate] Setting StHt: 1
2019-12-20 16:00:00 INFO (SyncWorker_1) [custom_components.gree.climate] Setting StHt: 0
2019-12-20 16:00:00 INFO (SyncWorker_2) [custom_components.gree.climate] Setting StHt: 0
2019-12-20 16:00:29 INFO (SyncWorker_0) [custom_components.gree.climate] Setting StHt: 1
2019-12-20 16:00:29 INFO (SyncWorker_1) [custom_components.gree.climate] Setting StHt: 0
2019-12-20 16:01:29 INFO (SyncWorker_2) [custom_components.gree.climate] Setting StHt: 0
2019-12-20 16:01:29 INFO (SyncWorker_1) [custom_components.gree.climate] Setting StHt: 1
2019-12-20 16:02:30 INFO (SyncWorker_0) [custom_components.gree.climate] Setting StHt: 1
2019-12-20 16:02:30 INFO (SyncWorker_1) [custom_components.gree.climate] Setting StHt: 0
2019-12-20 16:03:31 INFO (SyncWorker_4) [custom_components.gree.climate] Setting StHt: 1
2019-12-20 16:03:31 INFO (SyncWorker_0) [custom_components.gree.climate] Setting StHt: 0
2019-12-20 16:04:32 INFO (SyncWorker_3) [custom_components.gree.climate] Setting StHt: 1
2019-12-20 16:04:32 INFO (SyncWorker_0) [custom_components.gree.climate] Setting StHt: 0
2019-12-20 16:05:33 INFO (SyncWorker_1) [custom_components.gree.climate] Setting StHt: 0
2019-12-20 16:05:33 INFO (SyncWorker_3) [custom_components.gree.climate] Setting StHt: 1

**Comment by RobHofmann** [comment] 2020-01-07 20:08
Merged & Closed.

Released in 2.1.0. Can be updated through HACS.

**Closed by RobHofmann** 2020-01-07 20:08 UTC
Labels: RFC

**Comment by wacher74** [comment] 2020-01-07 21:22
Hi,

Thank you for support 8C :)

Here is a suggestion, just a little fix (sorry I don't know github enough)

    def UpdateHATargetTemperature(self):
        # Sync set temperature to HA
        if (int(self._acOptions['StHt']) == 1):
            self._target_temperature = 8
        else:
            self._target_temperature = self._acOptions['SetTem']
        _LOGGER.info('HA target temp set according to HVAC state to: ' + str(self._target_temperature))

Reason: AC reports the temperature what is set for normal heating (ex. 22). Gree+ app, A/C display shows 8C, according to reality.

**Comment by PLTorrent** [comment] 2020-01-07 23:37
Hi @wacher74, this is what I was missing. Will test if your proposed solution works as intended and if yes then I'll manage the github process. 

In the comments to my pull there is:

"The only thing missing is that when this mode is activated it would be good to display target temp as 8 deg C the same as on the device display. Maybe someone could add this or give me a hint how to do it quickly. Didn't want to mess up the temp refreshing/setting."

Will do my best to verify tomorrow.

**Comment by wacher74** [comment] 2020-01-08 07:06
Thank you for your help!
I just added an if statement to UpdateHATargetTemperature()
If StHt is active then 8 is reported to HomeAssistant instead of SetTem (which is temp for normal heating)

**Comment by PLTorrent** [comment] 2020-01-08 12:36
Just tested. Actually your solution is very clever one. I was afraid of some strange things happening with thermostat control since the range for this control is 16-30 deg C. However it all works really nice, since when AC is working in 8degC mode it ignores any input changing temp. Also clicking on the arrows of the thermostat only changes the temp for a couple of seconds and than it's all back to normal. I was afraid that changing temp might turn off the 8C mode.

Since this is a very nice solution I will make a pull request with your code. 

Thank you for your support!
