### ISSUE TITLE
Unable to start HA

### ISSUE THREAD

**Issue by alpetrov87** [RobHofmann/HomeAssistant-GreeClimateComponent#1] opened 2018-10-18 21:44 UTC
When I try to use your custom component I am facing issue that HA does not start. All I get is:
Oct 18 21:05:59 raspberrypi hass[31437]: 2018-10-18 21:05:59 INFO (MainThread) [custom_components.climate.gree] Fetching Device Encryption Key
Oct 18 21:05:59 raspberrypi hass[31437]: 2018-10-18 21:05:59 INFO (MainThread) [custom_components.climate.gree] GetDeviceKey()
Oct 18 21:05:59 raspberrypi hass[31437]: 2018-10-18 21:05:59 INFO (MainThread) [custom_components.climate.gree] Creating encryptor with Device Key
Oct 18 21:05:59 raspberrypi hass[31437]: 2018-10-18 21:05:59 INFO (MainThread) [custom_components.climate.gree] Encrypting Pack
Oct 18 21:05:59 raspberrypi hass[31437]: 2018-10-18 21:05:59 INFO (MainThread) [custom_components.climate.gree] Creating JSON
Oct 18 21:05:59 raspberrypi hass[31437]: 2018-10-18 21:05:59 INFO (MainThread) [custom_components.climate.gree] Fetching & Returning result
Oct 18 21:05:59 raspberrypi hass[31437]: 2018-10-18 21:05:59 INFO (MainThread) [custom_components.climate.gree] FetchResult(192.168.0.119, 7000, {"cid": "a..."uid": 0})
Oct 18 21:05:59 raspberrypi hass[31437]: 2018-10-18 21:05:59 INFO (MainThread) [custom_components.climate.gree] Creating sock
Oct 18 21:05:59 raspberrypi hass[31437]: 2018-10-18 21:05:59 INFO (MainThread) [custom_components.climate.gree] Sending over UDP
Oct 18 21:05:59 raspberrypi hass[31437]: 2018-10-18 21:05:59 INFO (MainThread) [custom_components.climate.gree] Receiving over UDP

And HA does not start. 
Do you have any idea what can cause this?

**Comment by knackrack615** [comment] 2018-11-26 03:46
Hello, exactly same issue here

Stuck on Receiving over UDP and HA never starts

**Comment by mihanich** [comment] 2018-12-27 08:53
same issue.
https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/blob/2e829aa43b103b717b0c162bd8d6a7c1192931e2/custom_components/climate/gree.py#L173

seems something goes wrong while UDP data receive.

@RobHofmann can you please help us to find out root cause?

**Comment by BennyAfriat** [comment] 2019-01-02 17:59
Same issue here!

**Comment by RobHofmann** [comment] 2019-04-03 20:48
This should be fixed with the latest version. Please let me know if you encounter any issues.

Thanks all!

**Closed by RobHofmann** 2019-04-03 20:48 UTC
