### ISSUE TITLE
No possible disable sleep

### ISSUE THREAD

**Issue by claudiosala80** [RobHofmann/HomeAssistant-GreeClimateComponent#44] opened 2019-11-24 20:31 UTC
**Describe the bug**
I added the option for sleep, with an input Boolean
When I set the button to true, the sleep is enabled on the final device.
If I make the button change status, the sleep is not disabled on the device

my yaml
- platform: gree
  name: Condizionatore camera
  host: 192.168.x.x
  port: 7000
  mac: '123456789'
  target_temp_step: 1
  sleep: input_boolean.bedroom_ac_sleep

**Platform:**
 - OS: Hassbian
 - Browser: Chrome
 - Version: 0.10x

**Comment by RobHofmann** [comment] 2019-11-25 17:18
How do you implement this boolean? Can you share the input_boolean.bedroom_ac_sleep entity?

**Comment by claudiosala80** [comment] 2019-11-25 20:41
input_boolean:
  bedroom_ac_sleep:
    name: Condizionatore camera sleep
    initial: off

**Comment by RobHofmann** [comment] 2019-11-26 10:48
Can you turn on debugging for this component and paste the debug log? The boolean seems fine.

**Comment by claudiosala80** [comment] 2019-11-26 15:28
Here!
When I turn on the device, it was with sleep on and the boolean on lovelace was correct.
I set it to off, the device did sound, but sleep still on and after a sync also on lovelace was still on

I did operation around 16:22

[[custom_components.gree.climate].log](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/files/3892567/custom_components.gree.climate.log)

**Comment by RobHofmann** [comment] 2019-11-26 16:25
Hmm. I dont use/have this feature, so its hard for me to debug.

@wjketting implemented this feature. maybe he can aid us with this issue.

**Comment by claudiosala80** [comment] 2019-11-26 17:13
I don't know python and so I don't how debug

**Comment by wacher74** [comment] 2019-12-21 21:38
I experienced similar strange thing about sleep mode, finally I gave it up and I implemented this feature via automation (temp decreasing/increasing + quiet mode at specified time).
I'm not use input_boolean for controling at all, because its icon don't change color (Home Assistant it is very messy in this term). I made template switches for control AC.
(Power on/off, Quiet mode and panel lights, Cold plasma/health)

**Comment by claudiosala80** [comment] 2019-12-23 09:42
> I experienced similar strange thing about sleep mode, finally I gave it up and I implemented this feature via automation (temp decreasing/increasing + quiet mode at specified time).
> I'm not use input_boolean for controling at all, because its icon don't change color (Home Assistant it is very messy in this term). I made template switches for control AC.
> (Power on/off, Quiet mode and panel lights, Cold plasma/health)

It is something you like to share with me?
I want "get inspiration" from what you did!

**Comment by wacher74** [comment] 2019-12-23 10:08
Here are some code snipet.
I have Gree Amber (climate.gree_ac_1).

```
## Switches for control
switch:
- platform: template
  switches:
    ac1_onoff:
        friendly_name: 'AC1 power'
        value_template: >-
          {% if states('climate.gree_ac_1') != 'off' %}
            on
          {% else %}
            off
          {% endif %}

        turn_on:
        - entity_id: climate.gree_ac_1
          service: climate.turn_on

        turn_off:
        - entity_id: climate.gree_ac_1
          service: climate.turn_off

    ac1_quiet:
        friendly_name: 'AC1 quiet mode'
        icon_template: 'mdi:headphones'
        value_template: >-
          {% if state_attr('climate.gree_ac_1', 'fan_mode') == 'Quiet' %}
            on
          {% else %}
            off
          {% endif %}

        turn_on:
        - entity_id: climate.gree_ac_1
          service: climate.set_fan_mode
          data:
            fan_mode: 'Quiet'

        turn_off:
        - entity_id: climate.gree_ac_1
          service: climate.set_fan_mode
          data:
            fan_mode: 'Auto'

    ac1_panel_light:
        friendly_name: 'AC1 panel light'
        icon_template: 'mdi:lightbulb-on'
        value_template: "{{ states('input_boolean.ac1_panel_light') }}"

        turn_on:
        - entity_id: input_boolean.ac1_panel_light
          service: input_boolean.turn_on

        turn_off:
        - entity_id: input_boolean.ac1_panel_light
          service: input_boolean.turn_off

    ac1_cold_plasma:
        friendly_name: 'AC1 Health (cold plasma)'
        icon_template: 'mdi:pine-tree'
        value_template: "{{ states('input_boolean.ac1_health') }}"

        turn_on:
        - entity_id: input_boolean.ac1_health
          service: input_boolean.turn_on

        turn_off:
        - entity_id: input_boolean.ac1_health
          service: input_boolean.turn_off





## temperature controlling at specified time, I use AC for heating now.
## 22:00 22C, quiet on
## 07:00 23C
## 08:00 24C, quiet off


automation:
- alias: 'Klíma fűtés, 22:00, 22 fok, quiet mode on'
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
    condition: state
    entity_id: climate.gree_ac_1
    state: 'heat'
  action:
    - service: switch.turn_on
      entity_id: switch.ac1_quiet # fan mode quiet
    - delay:
        seconds: 5
    - service: climate.set_temperature
      entity_id: climate.gree_ac_1
      data_template:
        temperature: 22


- alias: 'Klíma fűtés, 07:00, 23 fok'
  trigger:
  - platform: time
    at: '07:00:00'
  condition:
    condition: state
    entity_id: climate.gree_ac_1
    state: 'heat'
  action:
    - service: climate.set_temperature
      entity_id: climate.gree_ac_1
      data_template:
        temperature: 23

- alias: 'Klíma fűtés, 08:00, 24 fok, quiet mode off'
  trigger:
  - platform: time
    at: '08:00:00'
  condition:
    condition: state
    entity_id: climate.gree_ac_1
    state: 'heat'
  action:
    - service: switch.turn_off
      entity_id: switch.ac1_quiet # fan mode: Auto lesz
    - delay:
        seconds: 5
    - service: climate.set_temperature
      entity_id: climate.gree_ac_1
      data_template:
        temperature: 24

```

**Comment by claudiosala80** [comment] 2019-12-23 10:17
> Here are some code snipet.
> I have Gree Amber (climate.gree_ac_1).
> 
> ```
> ## Switches for control
> switch:
> - platform: template
>   switches:
>     ac1_onoff:
>         friendly_name: 'AC1 power'
>         value_template: >-
>           {% if states('climate.gree_ac_1') != 'off' %}
>             on
>           {% else %}
>             off
>           {% endif %}
> 
>         turn_on:
>         - entity_id: climate.gree_ac_1
>           service: climate.turn_on
> 
>         turn_off:
>         - entity_id: climate.gree_ac_1
>           service: climate.turn_off
> 
>     ac1_quiet:
>         friendly_name: 'AC1 quiet mode'
>         icon_template: 'mdi:headphones'
>         value_template: >-
>           {% if state_attr('climate.gree_ac_1', 'fan_mode') == 'Quiet' %}
>             on
>           {% else %}
>             off
>           {% endif %}
> 
>         turn_on:
>         - entity_id: climate.gree_ac_1
>           service: climate.set_fan_mode
>           data:
>             fan_mode: 'Quiet'
> 
>         turn_off:
>         - entity_id: climate.gree_ac_1
>           service: climate.set_fan_mode
>           data:
>             fan_mode: 'Auto'
> 
>     ac1_panel_light:
>         friendly_name: 'AC1 panel light'
>         icon_template: 'mdi:lightbulb-on'
>         value_template: "{{ states('input_boolean.ac1_panel_light') }}"
> 
>         turn_on:
>         - entity_id: input_boolean.ac1_panel_light
>           service: input_boolean.turn_on
> 
>         turn_off:
>         - entity_id: input_boolean.ac1_panel_light
>           service: input_boolean.turn_off
> 
>     ac1_cold_plasma:
>         friendly_name: 'AC1 Health (cold plasma)'
>         icon_template: 'mdi:pine-tree'
>         value_template: "{{ states('input_boolean.ac1_health') }}"
> 
>         turn_on:
>         - entity_id: input_boolean.ac1_health
>           service: input_boolean.turn_on
> 
>         turn_off:
>         - entity_id: input_boolean.ac1_health
>           service: input_boolean.turn_off
> 
> 
> 
> 
> 
> ## temperature controlling at specified time, I use AC for heating now.
> ## 22:00 22C, quiet on
> ## 07:00 23C
> ## 08:00 24C, quiet off
> 
> 
> automation:
> - alias: 'Klíma fűtés, 22:00, 22 fok, quiet mode on'
>   trigger:
>   - platform: time
>     at: '22:00:00'
>   condition:
>     condition: state
>     entity_id: climate.gree_ac_1
>     state: 'heat'
>   action:
>     - service: switch.turn_on
>       entity_id: switch.ac1_quiet # fan mode quiet
>     - delay:
>         seconds: 5
>     - service: climate.set_temperature
>       entity_id: climate.gree_ac_1
>       data_template:
>         temperature: 22
> 
> 
> - alias: 'Klíma fűtés, 07:00, 23 fok'
>   trigger:
>   - platform: time
>     at: '07:00:00'
>   condition:
>     condition: state
>     entity_id: climate.gree_ac_1
>     state: 'heat'
>   action:
>     - service: climate.set_temperature
>       entity_id: climate.gree_ac_1
>       data_template:
>         temperature: 23
> 
> - alias: 'Klíma fűtés, 08:00, 24 fok, quiet mode off'
>   trigger:
>   - platform: time
>     at: '08:00:00'
>   condition:
>     condition: state
>     entity_id: climate.gree_ac_1
>     state: 'heat'
>   action:
>     - service: switch.turn_off
>       entity_id: switch.ac1_quiet # fan mode: Auto lesz
>     - delay:
>         seconds: 5
>     - service: climate.set_temperature
>       entity_id: climate.gree_ac_1
>       data_template:
>         temperature: 24
> ```

I will try to use what you do for quiet for the sleep mode
Thanks for now

**Comment by claudiosala80** [comment] 2019-12-24 10:12
No working: the result is the same. 
I think there is a problem in one of the scripts

**Comment by claudiosala80** [comment] 2019-12-24 16:44
@RobHofmann and @wjketting

I did some test: with light, that seems the same, all it is ok.

With sleep this is what happen after I enable the switch in Home Assistant to stop the sleep
`2019-12-24 17:40:10 INFO (MainThread) [custom_components.gree.climate] sleep_entity state changed |input_boolean.living_ac_sleep|<state input_boolean.living_ac_sleep=on; icon=mdi:car @ 2019-12-24T17:38:40.270750+01:00>|<state input_boolean.living_ac_sleep=off; icon=mdi:car @ 2019-12-24T17:40:10.888039+01:00>
2019-12-24 17:40:10 INFO (MainThread) [custom_components.gree.climate] Updating HVAC with changed sleep_entity state |<state input_boolean.living_ac_sleep=off; icon=mdi:car @ 2019-12-24T17:40:10.888039+01:00>
2019-12-24 17:40:11 INFO (MainThread) [custom_components.gree.climate] HA sleep option set according to HVAC state to: off
2019-12-24 17:40:42 INFO (SyncWorker_2) [custom_components.gree.climate] HA sleep option set according to HVAC state to: off
2019-12-24 17:40:42 INFO (SyncWorker_1) [custom_components.gree.climate] HA sleep option set according to HVAC state to: on
2019-12-24 17:40:42 INFO (MainThread) [custom_components.gree.climate] sleep_entity state changed |input_boolean.living_ac_sleep|<state input_boolean.living_ac_sleep=off; icon=mdi:car @ 2019-12-24T17:40:10.888039+01:00>|<state input_boolean.living_ac_sleep=on; icon=mdi:car @ 2019-12-24T17:40:42.699876+01:00>
`

As you can see, one of the sync thread switch to on. I cannot understand if there is a problem in the perl script or it is a problem on Gree device that don't stop the sleep

**Comment by wjketting** [comment] 2019-12-25 10:34
@claudiosala80 

sorry for delayed respons.
switching sleep to off seems not to work for me either.
i'll try to look into it.

**Comment by wjketting** [comment] 2019-12-25 12:12
After a bit of testing it seems the problem is with the airco not accepting the status change for SwhSlp from 1 => 0, see summarised part of my log below.

The 8th parameter in the numbered list is SwhSlp (sleepmode). 
The scripts sends 0 (acOptions => statePackJson) and receives 1 (part after Done sending etc...) back from the airco.

- Overwriting SwhSlp: 0
- Done overwriting acOptions
- acOptions: {'Pow': 1, 'Mod': 1, 'SetTem': 20, 'WdSpd': 1, 'Air': 1, 'Blo': 0, 'Health': 0, 'SwhSlp': 0, 'Lig': 0, 'SwingLfRig': 0, 'SwUpDn': 4, 'Quiet': 2, 'Tur': 0, 'StHt': 0, 'TemUn': 0, 'HeatCoolType': 0, 'TemRec': 0, 'SvSt': 0}
- Start sending state to HVAC
- statePackJson: {"opt":["Pow","Mod","SetTem","WdSpd","Air","Blo","Health","SwhSlp","Lig","SwingLfRig","SwUpDn","Quiet","Tur","StHt","TemUn","HeatCoolType","TemRec","SvSt"],"p":[1,1,20,1,1,0,0,0,0,0,4,2,0,0,0,0,0,0],"t":"cmd"}
- Done sending state to HVAC: {'t': 'res', 'mac': 'f4911e1cddad', 'r': 200, 'opt': ['Pow', 'Mod', 'SetTem', 'WdSpd', 'Air', 'Blo', 'Health', 'SwhSlp', 'Lig', 'SwingLfRig', 'SwUpDn', 'Quiet', 'Tur', 'StHt', 'TemUn', 'HeatCoolType', 'TemRec', 'SvSt'], 'p': [1, 1, 20, 1, 1, 0, 0, 1, 0, 0, 4, 2, 0, 0, 0, 0, 0, 0], 'val': [1, 1, 20, 1, 1, 0, 0, 1, 0, 0, 4, 2, 0, 0, 0, 0, 0, 0]}

If you do the same for status change for SwhSlp from 0 => 1, the airco accepts the change.

Don't know the reason. With the Gree App it is possible to switch sleep on and off and select severall sleep modes (at least on my airo).
Maybe the payload used in the script is missing a parameter. 
Don't know how to check and solve this any further.

**Comment by claudiosala80** [comment] 2019-12-25 12:27
Thanks for your job!

This was also my suspect: since the light is working and the code is the
same, the problem is in the Gree device.

How home assistant call the device? Does it use the API?

Regards
Claudio

Il mer 25 dic 2019, 13:12 Wolter <notifications@github.com> ha scritto:

**Comment by claudiosala80** [comment] 2019-12-25 17:40
Hello Rob.

I found this project that is the base.
https://github.com/tomikaa87/gree-remote

I took a look and it seems that for sleep only 1 or 0 need to passed.
What is strange is why the Android app allow it. I will try to understand
how sniff the messages from app to device, but I don't know if I can do

Marry xmans
Claudio

Il giorno mer 25 dic 2019 alle ore 13:27 claudio sala <
claudiosala80@alice.it> ha scritto:

**Comment by PLTorrent** [comment] 2020-01-04 15:36
Hi,

I have compiled and run GreeRemoteAndroid from this repo and I can already tell you that with this it is also not possible to set sleep to off. You can only turn it on. A workaround is to switch to FAN mode or other mode that excludes sleep so sleep will be set to 0.

However it is much easier to experiment using this app, and also you have the source code so modifications are pretty straightforward.

**Comment by claudiosala80** [comment] 2020-01-04 18:04
Thanks a lot.

My idea is try to sniff the package that official app send, but I don't
know if it is possible and how long it will require to investigate

Il sab 4 gen 2020, 16:36 PLTorrent <notifications@github.com> ha scritto:

**Comment by PLTorrent** [comment] 2020-01-05 09:24
Leave that to me. Got them captured already. Just need to decode the packs and see whats inside. I'll compare them with what the custom app as well as Home Assistant is sending to the device. ;]

**Comment by claudiosala80** [comment] 2020-01-05 11:58
Is there any way I can help you on this decode?

Il dom 5 gen 2020, 10:24 PLTorrent <notifications@github.com> ha scritto:

**Comment by PLTorrent** [comment] 2020-01-05 15:56
Nah, it pretty simple reusing code from this repo in python script. Will you know what I have found.

**Comment by PLTorrent** [comment] 2020-01-05 17:01
Ok so this is how app does it:
Activate:
'opt': ['SwhSlp', 'SlpMod', 'SvSt', 'StHt'], 'p': [1, 1, 0, 0], 'val': [1, 1, 0, 0]}
Dev responds:
{'opt': ['SwhSlp', 'SlpMod', 'SvSt', 'StHt'], 'p': [1, 1, 0, 0], 't': 'cmd'}

Deactivate:
{'opt': ['SwhSlp', 'SlpMod'], 'p': [0, 0], 't': 'cmd'}
Dev responds:
{'opt': ['SwhSlp', 'SlpMod'], 'p': [0, 0], 'val': [0, 0]}

and then status message from device:
'cols': ['Pow', 'Mod', 'TemUn', 'SetTem', 'TemRec', 'HeatCoolType', 'WdSpd', 'Tur', 'Quiet', 'SwUpDn', 'SwingLfRig', 'Air', 'Blo', 'Health', 'SvSt', 'Lig', 'StHt', 'SwhSlp', 'SlpMod', 'AllErr'], 'dat': [1, 1, 0, 24, 0, 0, 1, 0, 0, 6, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0]

So it seems that to deactivate sleep mode app sends only 2 params: SwhSlp and SlpMod

**Comment by claudiosala80** [comment] 2020-01-05 20:09
Mmm...
And code of the plugin cannot be modified, correct?

Il dom 5 gen 2020, 18:01 PLTorrent <notifications@github.com> ha scritto:

**Comment by PLTorrent** [comment] 2020-01-05 22:12
I see not reason why the plugin cannot be modified by creator. After further analysis it seems that what the [https://github.com/tomikaa87/gree-remote](url) and here is missing is the SlpMod parameter.

**Comment by PLTorrent** [comment] 2020-01-06 09:11
Hi, forked a project and fixed the sleep mode. @claudiosala80  please check the sleep mode bugfix in my repo below and let me know if this works for you.

[https://github.com/PLTorrent/HomeAssistant-GreeClimateComponent/tree/sleep_mode_bugfix](url)

@wjketting you could check also if you have time. 

If all is ok I'll create a pull request later on.

Regards.

**Comment by claudiosala80** [comment] 2020-01-06 09:42
Wonderful
I will test during my afternoon!

Il lun 6 gen 2020, 10:11 PLTorrent <notifications@github.com> ha scritto:

**Comment by claudiosala80** [comment] 2020-01-06 15:54
Working!!!!
Wonderful!!!

Thanks a lot!

Il giorno lun 6 gen 2020 alle ore 10:42 claudio sala <claudiosala80@alice.it>
ha scritto:

**Comment by PLTorrent** [comment] 2020-01-06 17:16
You're welcome.

**Comment by RobHofmann** [comment] 2020-01-07 20:07
Merged & Closed

Version 2.1.0 released. Can be updates through HACS!

Thanks @Everyone for all of your efforts!

**Closed by RobHofmann** 2020-01-07 20:07 UTC
Labels: bug, help wanted
