### ISSUE TITLE
 Gree now sends its own temperature

### ISSUE THREAD

**Issue by bienias87** [RobHofmann/HomeAssistant-GreeClimateComponent#147] opened 2023-08-20 15:48 UTC
I have the Gree Bora, and after updating the firmware to V3.73, the AC now sends its own temperature. This can be observed on EWPE.

2023-08-20T15:45:16.067Z [info]: MQTT message received: ewpe-smart/f4911ec4bd2c/status {Pow:1, Mod:1, TemUn:0, SetTem:24, TemRec:0, WdSpd:1, Air:0, Blo:0, Health:1, SwhSlp:0, Lig:1, SwingLfRig:0, SwUpDn:2, Quiet:0, Tur:0, SvSt:0, **TemSen:24**}

Is it possible to integrate this as a temperature sensor in Home Assistant?

**Comment by ArveVM** [comment] 2023-09-19 11:05
in my Wilfa Narvik25 the epwe app is now not reporting temp,, but I believe it was when I first used the official integration ? 
 (which don't allow heatpump on different vlan :(  )
And for sure the climate-entity from the official integration had both temp and set-temp reported in the climate-entity - So it should be possible to get it back as a reporting entity (and choose if one want to use that or a better placed room-temp?

**Comment by rapi3** [comment] 2024-03-13 14:31
+1

**Comment by RobHofmann** [comment] 2024-05-13 09:23
Duplicate of https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/89

Closing this one.

**Closed by RobHofmann** 2024-05-13 09:23 UTC
