### ISSUE TITLE
3 climates

### ISSUE THREAD

**Issue by cyberfly79** [RobHofmann/HomeAssistant-GreeClimateComponent#63] opened 2020-06-16 21:00 UTC
Hi,

I have 3 gree climates, but unfortunately all three don’t work at the same time. What can I mess up with the setup?

Thanks
Cyber

**Comment by RobHofmann** [comment] 2020-06-18 09:34
Can you provide the config you used? I use 2 gree climates myself, which work perfectly fine.

Please provide the following information:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Configuration**
Share your YAML here

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Platform:**
 - OS: [e.g. HASSIO, Hassbian]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 0.92.1]

**Additional context**
Add any other context about the problem here.

**Comment by RobHofmann** [comment] 2020-07-06 07:13
Closing this for now. Feel free to reopen if something pops up!

**Closed by RobHofmann** 2020-07-06 07:13 UTC

**Comment by donminyon** [comment] 2020-07-13 15:18
Hi,

This is a raspberry pi 3b and raspbian. Home-assistant core running in docker (Home Assistant 0.111.3).
Very, very rarely all three climates work at the same time.
It’s like not waiting for an answer from the climate. They work perfectly from their own app. I tried to set the timeout but it didn't get any better.

It always responds to ping in about 1 ms.

![image](https://user-images.githubusercontent.com/67007847/87321251-4a0fbe00-c52c-11ea-81f9-c3b0edf66ea6.png)


yaml:
- platform: gree
  name: haloszoba
  host: 192.168.1.74
  mac: 'f4:91:1e:75:a2:3a'
- platform: gree
  name: foldszint
  host: 192.168.1.81
  mac: 'f4:91:1e:75:a2:a1'
- platform: gree
  name: vendegszoba
  host: 192.168.1.77
  mac: 'f4:91:1e:75:a2:47'

**Comment by cyberfly79** [comment] 2020-07-13 15:26
Hi,

This is a raspberry pi 3b and raspbian. Home-assistant core running in docker (Home Assistant 0.111.3).
Very, very rarely all three climates work at the same time.
It’s like not waiting for an answer from the climate. They work perfectly from their own app. I tried to set the timeout but it didn't get any better.

It always responds to ping in about 1 ms.

![image](https://user-images.githubusercontent.com/7328224/87322698-0453f500-c52e-11ea-81c0-87cb907da500.png)


yaml:

platform: gree
name: haloszoba
host: 192.168.1.74
mac: 'f4:91:1e:75:a2:3a'

platform: gree
name: foldszint
host: 192.168.1.81
mac: 'f4:91:1e:75:a2:a1'

platform: gree
name: vendegszoba
host: 192.168.1.77
mac: 'f4:91:1e:75:a2:47'

**Comment by cyberfly79** [comment] 2020-07-15 19:39
I turn on debug:
(there is always an answer to ping)

2020-07-15 19:30:02 INFO (MainThread) [custom_components.gree.climate] Setting up Gree climate platform
2020-07-15 19:30:02 INFO (MainThread) [custom_components.gree.climate] Adding Gree climate device to hass
2020-07-15 19:30:02 INFO (MainThread) [custom_components.gree.climate] Initialize the GREE climate device
2020-07-15 19:30:02 INFO (MainThread) [custom_components.gree.climate] Retrieving HVAC encryption key
2020-07-15 19:30:02 INFO (MainThread) [custom_components.gree.climate] Fetching(192.168.1.74, 7000, 10, {"cid": "app","i": 1,"pack": "6kwCFcGeYwZV+VyBpi5DSa9F/dzKt/YymGm5ZLrvh6mj9mrs/0p7GUTdWxmNaBUt","t":"pack","tcid":"f4911e75a23a","uid": 0})
2020-07-15 19:30:02 INFO (MainThread) [custom_components.gree.climate] Fetched device encrytion key: b'9Op2Rs5Uv8Xy1Ab4'
2020-07-15 19:30:02 INFO (MainThread) [custom_components.gree.climate] Setting up Gree climate platform
2020-07-15 19:30:02 INFO (MainThread) [custom_components.gree.climate] Adding Gree climate device to hass
2020-07-15 19:30:02 INFO (MainThread) [custom_components.gree.climate] Initialize the GREE climate device
2020-07-15 19:30:02 INFO (MainThread) [custom_components.gree.climate] Retrieving HVAC encryption key
2020-07-15 19:30:02 INFO (MainThread) [custom_components.gree.climate] Fetching(192.168.1.75, 7000, 10, {"cid": "app","i": 1,"pack": "6kwCFcGeYwZV+VyBpi5DSV4kLAzvnrzfGPNhb27XhI2j9mrs/0p7GUTdWxmNaBUt","t":"pack","tcid":"f4911e75a2a1","uid": 0})
2020-07-15 19:30:12 INFO (MainThread) [custom_components.gree.climate] Setting up Gree climate platform
2020-07-15 19:30:12 INFO (MainThread) [custom_components.gree.climate] Adding Gree climate device to hass
2020-07-15 19:30:12 INFO (MainThread) [custom_components.gree.climate] Initialize the GREE climate device
2020-07-15 19:30:12 INFO (MainThread) [custom_components.gree.climate] Retrieving HVAC encryption key
2020-07-15 19:30:12 INFO (MainThread) [custom_components.gree.climate] Fetching(192.168.1.77, 7000, 10, {"cid": "app","i": 1,"pack": "6kwCFcGeYwZV+VyBpi5DSZE04YLjDsSmOJuLMuqAiU+j9mrs/0p7GUTdWxmNaBUt","t":"pack","tcid":"f4911e75a247","uid": 0})
2020-07-15 19:30:22 INFO (MainThread) [custom_components.gree.climate] name(): haloszoba
2020-07-15 19:30:22 INFO (MainThread) [custom_components.gree.climate] Gree climate device added to hass()
2020-07-15 19:30:22 INFO (MainThread) [custom_components.gree.climate] Starting SyncState
2020-07-15 19:30:22 INFO (MainThread) [custom_components.gree.climate] Fetching(192.168.1.74, 7000, 10, {"cid":"app","i":0,"pack":"fPDi74KkUQsKEozf7UTelGVIJv1nnzwI312bHPLKLCheo4o6crfn7rDlmk9KOKyK1OX3NNAjr7r0PmKarsmKm5vkekJLU8htJsRWKU+eGy2HtdLCjHoaZ1VQ1YQBhcD/hAoOtYuuBBvqXsGHfYjVXPcJhJWGfqEXJeGRaQqdQ8f29tmNiVaoVlsuOWCSCSc0sl/Y9ZpEiax75PPcEQx8k7K4k4Q8FmjiW8oL7rGessM8kiShqYR1HaoxaqIRpYn6y5XS1hcaVNNX+4MXgdpf4XmZ7SR9qyahltuaNSwwhl4=","t":"pack","tcid":"f4911e75a23a","uid":0})
2020-07-15 19:30:32 ERROR (MainThread) [homeassistant.components.climate] Error while setting up gree platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/config/custom_components/gree/climate.py", line 115, in async_setup_platform
    GreeClimate(hass, name, ip_addr, port, mac_addr, timeout, target_temp_step, temp_sensor_entity_id, lights_entity_id, xfan_entity_id, health_entity_id, powersave_entity_id, sleep_entity_id, eightdegheat_entity_id, hvac_modes, fan_modes, swing_modes, encryption_key, uid)
  File "/config/custom_components/gree/climate.py", line 160, in __init__
    self._encryption_key = self.GetDeviceKey().encode("utf8")
  File "/config/custom_components/gree/climate.py", line 237, in GetDeviceKey
    return self.FetchResult(cipher, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['key']
  File "/config/custom_components/gree/climate.py", line 220, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out
2020-07-15 19:30:32 ERROR (MainThread) [homeassistant.components.climate] Error while setting up gree platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/config/custom_components/gree/climate.py", line 115, in async_setup_platform
    GreeClimate(hass, name, ip_addr, port, mac_addr, timeout, target_temp_step, temp_sensor_entity_id, lights_entity_id, xfan_entity_id, health_entity_id, powersave_entity_id, sleep_entity_id, eightdegheat_entity_id, hvac_modes, fan_modes, swing_modes, encryption_key, uid)
  File "/config/custom_components/gree/climate.py", line 160, in __init__
    self._encryption_key = self.GetDeviceKey().encode("utf8")
  File "/config/custom_components/gree/climate.py", line 237, in GetDeviceKey
    return self.FetchResult(cipher, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['key']
  File "/config/custom_components/gree/climate.py", line 220, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out
2020-07-15 19:30:32 ERROR (MainThread) [homeassistant.components.climate] Error while setting up gree platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 441, in _async_add_entity
    await entity.async_added_to_hass()
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/config/custom_components/gree/climate.py", line 760, in async_added_to_hass
    self.SyncState()
  File "/config/custom_components/gree/climate.py", line 410, in SyncState
    currentValues = self.GreeGetValues(optionsToFetch)
  File "/config/custom_components/gree/climate.py", line 241, in GreeGetValues
    return self.FetchResult(self.CIPHER, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['dat']
  File "/config/custom_components/gree/climate.py", line 220, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out

**Comment by RobHofmann** [comment] 2020-07-19 10:21
And if you add just 2? will it stay stable then? In my own setup I have 2 AC's which have been stable since the beginning.

I dont see any weird stuff in the logs other than Timeouts. I moved away from my RPi because it wasnt fast enough for my installation (I got a pretty extensive installation). So you could try to setup Home Assistant on some faster hardware maybe, just to test. Other than than I can't say anything else than "something doesnt respond in time", wether it be network, the ac or the hass installation.
